# Generated by Django 5.2 on 2025-05-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Ингредиент')),
                ('unit', models.CharField(max_length=64, verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Список ингредиентов',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('title', 'unit'), name='ingredient_unique_title_unit')],
            },
        ),
    ]
