# Generated by Django 5.2 on 2025-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='date_added',
            new_name='added_at',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_image', verbose_name='Фотография'),
        ),
    ]
